use_frameworks!

platform :ios, '13.0'

target 'C63Device_Example' do
  pod 'C63Device', :path => '../'

  target 'C63Device_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
